### ISSUE TITLE
Error on Start

### ISSUE THREAD

**Issue by zachsamuels** [nicolaskenner/python-fortnite-api-wrapper#15]
I am getting this error on my main log in line:
`    return datetime.strptime(isotime, '%Y-%m-%dT%H:%M:%S.%fZ')`
`TypeError: strptime() argument 1 must be str, not None`
Any reason why this is happening now, but not earlier? Please get back to me on what is wrong and how to fix it.

**Comment by nicolaskenner** [comment]
Have you changed your password recently? It could be that your account or client credentials are invalid. I will put authentication exceptions on my todo list so this is more clear.

**Comment by oconstrutor** [comment]
> Have you changed your password recently? It could be that your account or client credentials are invalid. I will put authentication exceptions on my todo list so this is more clear.

Also getting this... its was working fine...  Now even on my dev pc its not working..

`Traceback (most recent call last):
  File "C:\Users\Pichau\Google Drive\git\rFortniteBrasil\venv\lib\site-packages\discord\ext\commands\core.py", line 62, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Pichau\Google Drive\git\rFortniteBrasil\src\cogs\tracker.py", line 103, in nickauto
    password='**mypass**', email='**myemai**l')
  File "C:\Users\Pichau\Google Drive\git\rFortniteBrasil\venv\lib\site-packages\pfaw\core.py", line 24, in __init__
    expires_at = utils.convert_iso_time(token_response.get('expires_at'))
  File "C:\Users\Pichau\Google Drive\git\rFortniteBrasil\venv\lib\site-packages\pfaw\utils.py", line 6, in convert_iso_time
    return datetime.strptime(isotime, '%Y-%m-%dT%H:%M:%S.%fZ')
TypeError: strptime() argument 1 must be str, not None`
