### ISSUE TITLE
Getting friends does not work anymore

### ISSUE THREAD

**Issue by jeremyjohn** [nicolaskenner/python-fortnite-api-wrapper#19]
I get a 403 error
```
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    smittys_pals = fortnite.friends(username='Smitty Werbenjagermanjensen')
  File "/home/fn/.local/lib/python3.5/site-packages/pfaw/core.py", line 41,in friends
    response = self.session.get(constants.friends.format(player_id))
  File "/home/fn/.local/lib/python3.5/site-packages/pfaw/core.py", line 120,in get
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 840, in raise_f or_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://friends-public-service-prod06.ol.epicgames.com/friends/api/public/friends/9c9212603304472d831c03d0978d2bc1
```

**Comment by nicolaskenner** [comment]
I tested this method and it works correctly. The friends method is very limited as it only works for getting the friends of the authenticated account. You can't get the friend list of some random player.

**Comment by jeremyjohn** [comment]
What information can we get from that? 
Can we see their game status like kills and status and can we send them a DM?
or does it just show the friends and their IDs?
