### ISSUE TITLE
Getting unauthorized / not authenticated errors

### ISSUE THREAD

**Issue by devzspy** [nicolaskenner/python-fortnite-api-wrapper#7]
```
from pfaw import Fortnite,Platform
fortnite = Fortnite(fortnite_token='my_game_token', launcher_token='my_launcher_token', password='password', email='email')

player = fortnite.player(username='Ninja')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pfaw/core.py", line 28, in player
    response = self.session.get(constants.player.format(username))
  File "/usr/local/lib/python2.7/dist-packages/pfaw/core.py", line 78, in get
    response.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://persona-public-service-prod06.ol.epicgames.com/persona/api/public/account/lookup?q=Ninja
```

I converted the code from Python 3.X to Python 2.7 to work with a bot I've already wrote.

These calls were working the other day outside of the bot but now they don't. I've done a `pip install fortnite -U` to update and then a 3to2 after as well.

**Comment by nicolaskenner** [comment]
I just tested the player method and it's working for me. Maybe something is wrong with your tokens. Did you change your Epic Games password? Feel free to join the [Discord](https://discord.gg/AEfWXP9) for better assistance on this.

**Comment by devzspy** [comment]
Worked it out over Discord.

Thanks again!
